name: payday-debug-windows

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'unity的分支或标签'
        required: true
        default: "develop"
        type: string

# 参数通过创建模板的api，动态生成
env:
  flow_pg_name: "payday"
  # <仓库名>-<环境代号>
  flow_artifact_name: "payday-debug"
  flow_env: "Debug"
  flow_language_type: ""
  flow_language_version: ""
  flow_android_repo_type: "github"
  flow_android_repo_address: "aoemo-cc/UGameAndroid"
  flow_android_repo_user: ""
  flow_android_repo_password: "${{ secrets.GH_TOKEN }}"
  flow_unity_repo_type: "github"
  flow_unity_repo_address: "aoemo-cc/UGameFrame"
  # flow_unity_repo_address: "aoemo-cc/UGameFrame_Demo"
  flow_unity_repo_user: ""
  flow_unity_repo_password: "${{ secrets.GH_TOKEN }}"
  # flow_build_cmd: ""
  # flow_dependency_cmd: ""
  # flow_test_cmd: ""
  flow_channel_type: "feishu"
  flow_send_addr: ${{ secrets.FS_ROBOT }}

  flow_full_repo_addr: ""
  flow_wf_addr: "${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}"
  flow_actor: "${{ github.ACTOR }}"

jobs:
  build:
    name: 编译打包
    runs-on: windows-2022
    steps:
      - name: 解决git分支非最新导致错误
        shell: pwsh
        run: |
          Set-PSDebug -Trace 1
          git config --global user.name 'liuming'
          git config --global user.email 'liuming@aoemo.com'
          git add -A || true
          git commit -m "workflow编译临时使用" || true
          # try {
          #     git config --global user.name 'liuming'
          #     git config --global user.email 'liuming@aoemo.com'
          #     git add -A
          #     if ($LASTEXITCODE -eq 0) {
          #         git commit -m "workflow编译临时使用"
          #     }
          # }
          # catch {
          #     Write-Output "没有缓存，无需git提交" -ForegroundColor Yellow
          #     $error[0] | Out-String
          # }
      - name: 测试
        run: echo "Hello world"
        
      # - name: 配置ndk环境
      #   id: setup-ndk
      #   uses: nttld/setup-ndk@v1.4.2
      #   with:
      #     ndk-version: r19
      #     local-cache: true
      #     link-to-sdk: true
      # - name: 验证ndk环境
      #   run: |
      #     Set-PSDebug -Trace 1
      #     Write-Host "当前路径: $(pwd)" -ForegroundColor Yellow
      #     Write-Host "安装目录：${{ steps.setup-ndk.outputs.ndk-path }}" -ForegroundColor Yellow
      #     cd ${{ steps.setup-ndk.outputs.ndk-path }}
      #     Write-Host "新的当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      #     cat ./source.properties

      # - name: 配置java环境
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 11
          
      # - name: 配置Gradle环境
      #   uses: gradle/gradle-build-action@v2
      #   with:
      #     gradle-version: 6.5
      # - name: 验证Gradle环境
      #   run: Write-Host "gradle版本：$(gradle -v)" -ForegroundColor Yellow
        
      # # - name: 预建目录
      # #   run: mkdir -v actions_temp UGameAndroid UGameFrame
      # # - name: 拉取自定义的action
      # #   uses: actions/checkout@v4.1.1
      # #   with:
      # #     path: 'actions_temp'
          
      # # # - name: 拉安卓代码
      # # #   uses: ./actions_temp/.github/actions/action-checkout
      # # #   with:
      # # #     repo_type: "${{ env.flow_android_repo_type }}"
      # # #     repository: "${{ env.flow_android_repo_address }}"
      # # #     ref: "${{ env.flow_pg_name }}"
      # # #     username: "${{ env.flow_android_repo_user }}"
      # # #     password: "${{ env.flow_android_repo_password }}"
      # # #     root_dir: "UGameAndroid"
          
      # - name: 拉安卓代码
      #   uses: actions/checkout@v4.1.1
      #   with:
      #     repository: "${{ env.flow_android_repo_address }}"
      #     ref: "_account_${{ env.flow_pg_name }}"
      #     token: "${{ env.flow_android_repo_password }}"
      #     path: "UGameAndroid"

      # - name: 验证拉取操作
      #   run: |
      #     Set-PSDebug -Trace 1
      #     Write-Host "当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      #     Write-Host "查看安卓分支" -ForegroundColor Yellow
      #     cd UGameAndroid
      #     git remote -v && git branch
      #     Write-Host "新的当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      
      # - name: 清理旧Unity资源
      #   working-directory: UGameAndroid
      #   run: |
      #     Set-PSDebug -Trace 1
      #     Remove-Item -Path "unityLibrary\*" -ErrorAction SilentlyContinue -Force -Recurse
          
      # # # - name: 拉unity代码
      # # #   uses: ./actions_temp/.github/actions/action-checkout
      # # #   with:
      # # #     repo_type: "${{ env.flow_unity_repo_type }}"
      # # #     repository: "${{ env.flow_unity_repo_address }}"
      # # #     ref: "${{ inputs.ref }}"
      # # #     username: "${{ env.flow_unity_repo_user }}"
      # # #     password: "${{ env.flow_unity_repo_password }}"
      # # #     root_dir: "UGameFrame"
          
      # - name: 拉unity代码
      #   uses: actions/checkout@v4.1.1
      #   with:
      #     repository: "${{ env.flow_unity_repo_address }}"
      #     ref: "${{ inputs.ref }}"
      #     token: "${{ env.flow_unity_repo_password }}"
      #     path: "UGameFrame"

      # - name: 验证拉取操作
      #   run: |
      #     Set-PSDebug -Trace 1
      #     Write-Host "当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      #     Write-Host "查看安卓分支" -ForegroundColor Yellow
      #     cd UGameFrame
      #     git remote -v && git branch
      #     Write-Host "新的当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      
      # - name: Library缓存
      #   uses: actions/cache@v3.3.2
      #   with:
      #     path: UGameFrame/${{ env.flow_pg_name }}_UClient/Library
      #     key: Library-unity-${{ GITHUB.WORKFLOW }}-${{ GITHUB.RUN_NUMBER }}
      #     restore-keys: Library-unity-${{ GITHUB.WORKFLOW }}
      # - name: 解决git分支非最新导致错误
      #   shell: pwsh
      #   working-directory: UGameFrame
      #   run: |
      #     Set-PSDebug -Trace 1
      #     try {
      #         git config --global user.name 'liuming'
      #         git config --global user.email 'liuming@aoemo.com'
      #         git add -A
      #         if ($LASTEXITCODE -eq 0) {
      #             git commit -m "workflow编译临时使用"
      #         }
      #     }
      #     catch {
      #         Write-Output "没有缓存，无需git提交" -ForegroundColor Yellow
      #         $error[0] | Out-String
      #     }
      # # - name: 清理ubuntu磁盘空间(非必须)
      # #   uses: jlumbroso/free-disk-space@v1.3.1
      
      # - name: Unity编译
      #   uses: game-ci/unity-builder@v4.1.3
      #   env:
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #     UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      #   with:
      #     targetPlatform: Android
      #     unityVersion: 2020.3.45f1
      #     projectPath: UGameFrame/${{ env.flow_pg_name }}_UClient
      #     buildMethod: BuildProjectApkClientTool.BuildUnitySyncAndroidStudio
      #     customParameters: -logFile unity_build.log -batchmode -quit
      #     # customParameters: -batchmode -executeMethod BuildProjectApkClientTool.BuildUnitySyncAndroidStudio -quit

      # # - name: 调试环境
      # #   env:
      # #     TMATE_ENCRYPT_PASSWORD: ${{secrets.TMATE_ENCRYPT_PASSWORD}}
      # #     SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
      # #   uses: tete1030/safe-debugger-action@v1.01
          
      # - name: 验证
      #   run: |
      #     Set-PSDebug -Trace 1
      #     ls UGameFrame\${{ env.flow_pg_name }}_UClient\
      #     ls UGameFrame\${{ env.flow_pg_name }}_UClient\_ObfuscatorNameTranslation.txt
      #     cat UGameFrame\${{ env.flow_pg_name }}_UClient\_ObfuscatorNameTranslation.txt
      #     tree UGameAndroid/unityLibrary\src\main\Il2CppOutputProject\
          
      # - name: 生成local.properties
      #   working-directory: UGameAndroid
      #   run: |
      #     Set-Content -Path local.properties -Value "sdk.dir=${ANDROID_HOME}`nndk.dir=${{ steps.setup-ndk.outputs.ndk-path }}"
      #     if (Test-Path .\local.properties) { Get-Content .\local.properties }
          
      # - name: gradlew打包
      #   working-directory: UGameAndroid
      #   run: |
      #     Set-PSDebug -Trace 1
      #     Write-Host "当前路径: $(pwd)" -ForegroundColor Yellow
      #     ls
      #     Write-Host "查看安卓相关目录" -ForegroundColor Yellow
      #     ls ${ANDROID_HOME}
      #     Write-Host "查看gradlew文件信息" -ForegroundColor Yellow
      #     (Get-Acl "gradlew").Access
      #     ls ./gradlew
          
      #     $_flow_pg_name = ${{ env.flow_pg_name }}
      #     $_flow_pg_name = $_flow_pg_name.Substring(0,1).ToUpper() + $_flow_pg_name.Substring(1)
      #     Write-Host "执行 ./gradlew clean" -ForegroundColor Yellow
      #     ./gradlew clean
      #     Write-Host "执行 ./gradlew clean bundle${_flow_pg_name}${{ env.flow_env }}" -ForegroundColor Yellow
      #     ./gradlew clean bundle${_flow_pg_name}${{ env.flow_env }}
          
      #     Write-Host "查看app/build/outputs/apk/release目录下内容" -ForegroundColor Yellow
      #     Get-Location
      #     if (Test-Path -Path 'app\build\outputs\apk\release') { 
      #       Get-ChildItem -Path 'app\build\outputs\apk\release' | Sort-Object -Property LastWriteTime -Descending 
      #     }
      #     Write-Host "查看outputs目录全部信息" -ForegroundColor Yellow
      #     tree app\build\outputs\apk\release
      #     Write-Host "查看符号表目录全部信息" -ForegroundColor Yellow
      #     tree unityLibrary\symbols
    
      # - name: 上传apk
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: apk_1
      #     path: |
      #       app/build/outputs/apk/release/app-release.apk
    
      # - name: 上传json文件
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: json_1
      #     path: app/build/outputs/apk/release/output-metadata.json
          
          
