name: ugameandroid-debug

on:
  workflow_dispatch:
    inputs:
      ref:
        description: '分支或标签(正式使用的时候不要给默认值)'
        required: true
        type: string

# 参数通过创建模板的api，动态生成
env:
  # <仓库名>-<环境代号>
  flow_artifact_name: "ugameandroid-debug"
  flow_env: "Debug"
  flow_language_type: ""
  flow_language_version: ""
  flow_repository_type: "github"
  flow_repository_address: "aoemo-cc/UGameAndroid"
  flow_repository_user: ""
  flow_repository_password: "${{ secrets.GH_TOKEN }}"
  # flow_build_cmd: ""
  # flow_dependency_cmd: ""
  # flow_test_cmd: ""
  flow_channel_type: "feishu"
  flow_send_addr: ${{ secrets.FS_ROBOT }}

  flow_full_repo_addr: ""
  flow_wf_addr: "${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}"
  flow_actor: "${{ github.ACTOR }}"

jobs:
  build:
    name: 编译打包
    runs-on: ubuntu-latest
    steps:
      - name: 创建action存放目录
        run: mkdir -v actions_temp UGameAndroid UGameFrame
      - name: 拉取自定义的action
        uses: actions/checkout@v4.1.1
        with:
          path: 'actions_temp'
          
      - name: 拉安卓代码
        uses: ./actions_temp/.github/actions/action-checkout
        with:
          repo_type: "${{ env.flow_repository_type }}"
          repository: "${{ env.flow_repository_address }}"
          ref: "${{ inputs.ref }}"
          username: "${{ inputs.flow_repository_user }}"
          password: "${{ env.flow_repository_password }}"
          root_dir: "UGameAndroid"
          
      - name: 拉unity代码
        uses: ./actions_temp/.github/actions/action-checkout
        with:
          repo_type: "${{ env.flow_repository_type }}"
          repository: "${{ env.flow_repository_address }}"
          ref: "${{ inputs.ref }}"
          username: "${{ inputs.flow_repository_user }}"
          password: "${{ env.flow_repository_password }}"
          root_dir: "UGameFrame"
      
      - name: 验证拉取操作
        run: pwd && ls -t1
        
      - name: 配置java环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          
      - name: 配置Gradle环境
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      
      - name: gradlew打包
        run: |
          echo -e "gradle版本：$(gradle -v)"
          gradle assembleRelease
          pwd && [[ -d 'app/build/outputs/apk/release' ]] && ls -t1 app/build/outputs/apk/release
      
      - name: 配置unity环境
        run: echo "安装unity"
    
      # - name: 上传apk
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: apk_1
      #     path: |
      #       app/build/outputs/apk/release/app-release.apk
    
      # - name: 上传json文件
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: json_1
      #     path: app/build/outputs/apk/release/output-metadata.json

      - name: 通知
        run: echo "我是通知操作"
